export enum ActionType {
    CHANGE_PRESENTATION_TITLE = 'CHANGE_PRESENTATION_TITLE',

    //ElementsActions
    MOVE_ELEMENTS_TO_BACKGROUND_OR_FOREGROUND = 'MOVE_ELEMENTS_TO_BACKGROUND_OR_FOREGROUND',
    CHANGE_ELEMENTS_SIZE = 'CHANGE_ELEMENTS_SIZE',
    CHANGE_ELEMENTS_OPACITY = 'CHANGE_ELEMENTS_OPACITY',
    REMOVE_SELECTED_ELEMENTS = 'REMOVE_SELECTED_ELEMENTS',
    CHANGE_ELEMENTS_POSITION = 'CHANGE_ELEMENTS_POSITION',
    //ElementsActions
}