export enum ViewActionType {
    SET_ACTIVE_VIEW_AREA = 'SET_ACTIVE_VIEW_AREA',
    SET_APP_MODE = 'SET_APP_MODE',
    SET_CHOSEN_ELEMENTS_TYPE = 'SET_CHOSEN_ELEMENTS_TYPE',
    SET_TOOL_STATE = 'SET_TOOL_STATE',
}
