export enum ViewActionType {
    SET_ACTIVE_VIEW_AREA = 'SET_ACTIVE_VIEW_AREA',
    SET_APP_MODE = 'SET_APP_MODE',
    SET_ELEMENTS_RENDER_RATIO = 'SET_ELEMENTS_RENDER_RATIO',
    SET_CHOSEN_ELEMENTS_TYPE = 'SET_CHOSEN_ELEMENTS_TYPE',
    SET_TOOL_STATE = 'SET_TOOL_STATE',
    SET_SLIDE_CONTAINER_DIMENSIONS = 'SET_SLIDE_CONTAINER_DIMENSIONS',
    SET_SLIDE_TO_CONTAINER_RATIO = 'SET_SLIDE_TO_CONTAINER_RATIO',
    SET_SLIDE_WHITE_AREA_LOCATION = 'SET_SLIDE_WHITE_AREA_LOCATION',
    SET_SLIDE_VIEWBOX = 'SET_SLIDE_VIEWBOX',
    SET_WINDOW_RATIO = 'SET_WINDOW_RATIO',
}
